import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
// import AuthProvider from "../components/AuthProvider/AuthProvider"; // Adjusted import if using TypeScript (.tsx)
import { Suspense } from "react";
// import { Analytics } from "@vercel/analytics/react";
import Providers from '@/components/providers/providers';
import { Toaster } from '@/components/ui/sonner';
import { Lato } from 'next/font/google';

// Import Lato font globally
const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'], // Add all weights you want to support
  style: ['normal', 'italic'], // Add styles like normal and italic
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <AuthProvider>
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          lato.className
        )}>
        <Suspense>
          <Providers>
            {children}
          </Providers>
        </Suspense>

        {/* <Analytics /> */}
        <Toaster />
      </body>
    </html>
    // </AuthProvider>
  );
}
